version: "3"

services:
  myfinances_django:
    restart: always
    build:
      context: .
      dockerfile: infrastructure/backend/Dockerfile
    ports:
      - '9012:9012'
    volumes:
      - ../../:/MyFinances
    environment:
      TEST: "True"
      SECRET_KEY: mysecretkey
      URL: 127.0.0.1
      PROXY_IP: localhost
      BRANCH: debug
      DEBUG: "True"